HERO_INFO = {
    "wukong": {"full": "Wukong", "short": "Wuk"},
    "louis ix": {"full": "Louis IX", "short": "Louis"},
    "tutankhamun": {"full": "Tutankhamun", "short": "Tut"},
    "khubilai khan": {"full": "Khubilai Khan", "short": "Khan"},
    "manco": {"full": "Manco", "short": "Manco"},
    "alexander the great": {"full": "Alexander The Great", "short": "Alex"},
    "hippolyta": {"full": "Hippolyta", "short": "Hip"},
    "william": {"full": "William", "short": "Will"},
    "attila the hun": {"full": "Attila The Hun", "short": "Attila"},
    "saladin": {"full": "Saladin", "short": "Sal"},
    "muhammad ii": {"full": "Muhammad II", "short": "Muh"},
    "siegfried": {"full": "Siegfried", "short": "Sieg"},
    "peter the great": {"full": "Peter The Great", "short": "Peter"},
    "ramesses ii": {"full": "Ramesses II", "short": "Ram"},
    "hannibal barca": {"full": "Hannibal Barca", "short": "Hann"},
    "herald": {"full": "Herald", "short": "Herald"},
    "frederick": {"full": "Frederick", "short": "Fred"},
    "loki": {"full": "Loki", "short": "Loki"},
    "hammurabi": {"full": "Hammurabi", "short": "Ham"},
    "himiko": {"full": "Himiko", "short": "Him"},
    "empress wu": {"full": "Empress Wu", "short": "Wu"},
    "baldwin iv": {"full": "Baldwin IV", "short": "Bald"},
    "merlin": {"full": "Merlin", "short": "Mer"},
    "cleopatra": {"full": "Cleopatra", "short": "Cleo"},
    "bjorn": {"full": "Bjorn", "short": "Bjorn"},
    "king arthur": {"full": "King Arthur", "short": "Arthur"},
    "el cid": {"full": "El Cid", "short": "Cid"},
    "leonidas": {"full": "Leonidas", "short": "Leo"},
    "julius caesar": {"full": "Julius Caesar", "short": "JC"},
    "charles": {"full": "Charles", "short": "Char"},
    "ragnar": {"full": "Ragnar", "short": "Rag"},
    "trajan": {"full": "Trajan", "short": "Traj"},
    "tokugawa": {"full": "Tokugawa", "short": "Toku"},
    "gilgamesh": {"full": "Gilgamesh", "short": "Gil"},
    "elizabeth bathory": {"full": "Elizabeth Bathory", "short": "Liz"},
    "yoshitsune": {"full": "Yoshitsune", "short": "Yoshi"},
    "yi seong-gye": {"full": "Yi Seong-Gye", "short": "Yi"},
    "ashoka": {"full": "Ashoka", "short": "Ash"},
    "genghis khan": {"full": "Genghis Khan", "short": "GK"},
    "arash": {"full": "Arash", "short": "Arash"},
    "atalanta": {"full": "Atalanta", "short": "Ata"},
    "seondeok": {"full": "Seondeok", "short": "Seon"},
    "margaret i": {"full": "Margaret I", "short": "Marg"},
    "nebuchadnezzar ii": {"full": "Nebuchadnezzar II", "short": "Neb"},
}

# Example: only TL;DR builds placeholders
HERO_BUILDS = {name: f"✨ TL;DR – Best Artifact for {info['full']}\n⭐ Best Artifact: Unknown\n⚔️ Best Main Stat: Unknown\n⚡ Best Passive Roll: Unknown\n🔁 Alternative Passive: Unknown" 
               for name, info in HERO_INFO.items()}
