HERO_INFO = {
    "wukong": {"full": "Wukong", "short": "Wuk", "role": "Attack"},
    "louis ix": {"full": "Louis IX", "short": "Louis", "role": "Attack"},
    "tutankhamun": {"full": "Tutankhamun", "short": "Tut", "role": "Mage"},
    "khubilai khan": {"full": "Khubilai Khan", "short": "Khan", "role": "Attack"},
    "manco": {"full": "Manco", "short": "Manco", "role": "Tank"},
    "alexander the great": {"full": "Alexander The Great", "short": "Alex", "role": "Attack"},
    "hippolyta": {"full": "Hippolyta", "short": "Hip", "role": "Attack"},
    "william": {"full": "William", "short": "Will", "role": "Tank"},
    "attila the hun": {"full": "Attila The Hun", "short": "Attila", "role": "Attack"},
    "saladin": {"full": "Saladin", "short": "Sal", "role": "Tank"},
    "muhammad ii": {"full": "Muhammad II", "short": "Muh", "role": "Attack"},
    "siegfried": {"full": "Siegfried", "short": "Sieg", "role": "Attack"},
    "peter the great": {"full": "Peter The Great", "short": "Peter", "role": "Tank"},
    "ramesses ii": {"full": "Ramesses II", "short": "Ram", "role": "Ranged"},
    "hannibal barca": {"full": "Hannibal Barca", "short": "Hann", "role": "Attack"},
    "herald": {"full": "Herald", "short": "Herald", "role": "Attack"},
    "frederick": {"full": "Frederick", "short": "Fred", "role": "Tank"},
    "loki": {"full": "Loki", "short": "Loki", "role": "Attack"},
    "hammurabi": {"full": "Hammurabi", "short": "Ham", "role": "Mage"},
    "himiko": {"full": "Himiko", "short": "Him", "role": "Mage"},
    "empress wu": {"full": "Empress Wu", "short": "Wu", "role": "Mage"},
    "baldwin iv": {"full": "Baldwin IV", "short": "Bald", "role": "Mage"},
    "merlin": {"full": "Merlin", "short": "Mer", "role": "Mage"},
    "cleopatra": {"full": "Cleopatra", "short": "Cleo", "role": "Mage"},
    "bjorn": {"full": "Bjorn", "short": "Bjorn", "role": "Attack"},
    "king arthur": {"full": "King Arthur", "short": "Arthur", "role": "Tank"},
    "el cid": {"full": "El Cid", "short": "Cid", "role": "Ranged"},
    "leonidas": {"full": "Leonidas", "short": "Leo", "role": "Tank"},
    "julius caesar": {"full": "Julius Caesar", "short": "JC", "role": "Tank"},
    "charles": {"full": "Charles", "short": "Char", "role": "Attack"},
    "ragnar": {"full": "Ragnar", "short": "Rag", "role": "Tank"},
    "trajan": {"full": "Trajan", "short": "Traj", "role": "Tank"},
    "tokugawa": {"full": "Tokugawa", "short": "Toku", "role": "Tank"},
    "gilgamesh": {"full": "Gilgamesh", "short": "Gil", "role": "Ranged"},
    "elizabeth bathory": {"full": "Elizabeth Bathory", "short": "Liz", "role": "Mage"},
    "yoshitsune": {"full": "Yoshitsune", "short": "Yoshi", "role": "Ranged"},
    "yi seong-gye": {"full": "Yi Seong-Gye", "short": "Yi", "role": "Attack"},
    "ashoka": {"full": "Ashoka", "short": "Ash", "role": "Attack"},
    "genghis khan": {"full": "Genghis Khan", "short": "GK", "role": "Attack"},
    "arash": {"full": "Arash", "short": "Arash", "role": "Ranged"},
    "atalanta": {"full": "Atalanta", "short": "Ata", "role": "Ranged"},
    "seondeok": {"full": "Seondeok", "short": "Seon", "role": "Support"},
    "margaret i": {"full": "Margaret I", "short": "Marg", "role": "Support"},
    "nebuchadnezzar ii": {"full": "Nebuchadnezzar II", "short": "Neb", "role": "Tank"},
}

HERO_PRICE = {
    "wukong": "🐳 Whale Tier",
    "louis ix": "❄️ KVK Exclusive",
    "tutankhamun": "💰 High Tier",
    "khubilai khan": "💰 High Tier",
    "manco": "💰 High Tier",
    "alexander the great": "👑📜 Premium/Gems",
    "hippolyta": "🆓 Free-to-Play Friendly",
    "william": "🆓 Free-to-Play Friendly",
    "attila the hun": "👑📜 Premium/Gems",
    "saladin": "👑📜 Premium/Gems",
    "muhammad ii": "💰 High Tier",
    "siegfried": "💰 High Tier",
    "peter the great": "🆓 Free-to-Play Friendly",
    "ramesses ii": "👑📜 Premium/Gems",
    "hannibal barca": "🆓 Free-to-Play Friendly",
    "herald": "🆓 Free-to-Play Friendly",
    "frederick": "🆓 Free-to-Play Friendly",
    "loki": "🐳 Whale Tier",
    "hammurabi": "👑 Premium",
    "himiko": "💰 High Tier",
    "empress wu": "🆓 Free-to-Play Friendly",
    "baldwin iv": "👑📜 Premium/Gems",
    "merlin": "💵 Low/Mid Spending",
    "cleopatra": "🆓 Free-to-Play Friendly",
    "bjorn": "💰 High Tier",
    "king arthur": "🆓 Free-to-Play Friendly",
    "el cid": "👑📜 Premium/Gems",
    "leonidas": "🆓 Free-to-Play Friendly",
    "julius caesar": "🆓 Free-to-Play Friendly",
    "charles": "👑📜 Premium/Gems",
    "ragnar": "❄️ KVK Exclusive",
    "trajan": "❄️ KVK Exclusive",
    "tokugawa": "❄️ KVK Exclusive",
    "gilgamesh": "🆓 Free-to-Play Friendly",
    "elizabeth bathory": "💰👑📜 Premium/Gems",
    "yoshitsune": "🆓 Free-to-Play Friendly",
    "yi seong-gye": "🆓 Free-to-Play Friendly",
    "ashoka": "🆓 Free-to-Play Friendly",
    "genghis khan": "👑📜 Premium/Gems",
    "arash": "🆓 Free-to-Play Friendly",
    "atalanta": "👑 Premium",
    "seondeok": "❄️ KVK Exclusive",
    "margaret i": "❄️ KVK Exclusive",
    "nebuchadnezzar ii": "💰 High Tier",
}
